export const dynamic = 'force-dynamic'
import "./globals.css";
import NavBar from "./components/NavBar";
import { Inter } from "next/font/google";
import Providers from "./providers";
import Footer from "./components/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="cardoctor"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <Providers>
          <header>
            <div className="max-w-7xl mx-auto lg:px-8 md:px-4 px-2">
              <NavBar />
            </div>
          </header>
          <main>
            <div className="max-w-7xl mx-auto lg:px-8 md:px-4 px-2">
              {children}
            </div>
          </main>
          <footer className=" bg-main-dark mt-15 md:mt-25 lg:mt-32.5">
            <div className="max-w-7xl mx-auto lg:px-8 md:px-4 px-2">
              <Footer />
            </div>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
