import "./globals.css";
import NavBar from "./components/NavBar";
import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="cardoctor"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <header>
          <div className="max-w-7xl mx-auto lg:px-8 md:px-4 px-2">
            <NavBar />
          </div>
        </header>
        <main>
          <div className="max-w-7xl mx-auto lg:px-8 md:px-4 px-2">
            {children}
          </div>
        </main>
        <footer></footer>
      </body>
    </html>
  );
}
